version: '3.5'
services:
  sentinel1:
    container_name: sentinel1
    image: redis
    restart: always
    ports:
      - 26379:26379
    volumes:
      - ./redis-sentinel-1.conf:/usr/local/etc/redis/redis-sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
  sentinel2:
    container_name: sentinel2
    image: redis
    restart: always
    ports:
      - 26380:26380
    volumes:
      - ./redis-sentinel-2.conf:/usr/local/etc/redis/redis-sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
  sentinel3:
    container_name: sentinel3
    image: redis
    restart: always
    ports:
      - 26381:26381
    volumes:
      - ./redis-sentinel-3.conf:/usr/local/etc/redis/redis-sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf"]
networks:
  default:
    name: mybridge
    external: true